% NOTE: all compiler variables minused by 1 are affiliated with _M1

fid = fopen('parameters.csv', 'w');

fprintf(fid, ...
[
'idx,', ...             
'NUM_LAYER,', ...       
'LAYER_TYPE,', ...      
'INPX_BUF_MODE,', ...   
'WT_BUF_MODE,', ...     
'OUTPX_BUF_MODE,', ...  
'PAD,', ...             
'STRIDE,', ...
'RDADDR_ROTATE_EN,', ...
'TIX,', ...             
'TIY,', ...             
'TIF,', ...             
'TOF,', ...             
'WITH_RELU,', ...       
'WITH_BIAS,', ...       
'INBUF_RDADDR_KEY,', ...
'KX_KY,', ...
'NKX,', ...
'NKY,', ... 
'PAD_DIV_STRIDE,', ...
'LBUF_WREN,', ...
'LBUF_RDEN,', ...
'TOY_IS_NOY,', ...
'MAX_PAD_STR,', ...
'TOX_GRP,', ...                        
'TOY_GRP,', ...                                 
'TOF_GRP,', ...     
'TOXDMA_GRP,', ...
'END_TOYPAD,', ...                              
'END_NOYPAD,', ...                              
'PAD_E_CV_POX,', ...                            
'PAD_S_CV_POY,', ...                            
'PAD_E_CV_NKX,', ...                            
'PAD_S_CV_NKY,', ...                            
'PAD_N_CV_POY,', ...                            
'PAD_N_CV_NKY,', ...                            
'PAD_E_END_PLMX,', ...                          
'PAD_S_END_PLMX,', ...                          
'NUM_TIXGRP_PLMX,', ...                         
'TIXGRP1ST_PLMX,', ...                          
'TIXY1ST_PLMX,', ...                            
'LOC_PAD_E_PL,', ...                            
'LOC_PAD_S_PL,', ...                            
'WORDS_RDPX,', ...                              
'WORDS_WRPX,', ...                              
'NUM_ROWSTR,', ...                              
'END_ROW,', ...                                 
'END_ROW_STR,', ...                             
'TOF1OUPX_BSCV,', ...                           
'ACCU_TOF_BSCV,', ...                           
'NOY_GRP,', ...                                 
'NOF_GRP,', ...                                 
'TIX1POX_STR,', ...                             
'TIX1POX_TIY1POY,', ...                         
'END_ROWPOY,', ...                              
'TOXGRP_POY,', ...                              
'TOXGRP_TOY,', ...                              
'KX_KY_TIF,', ...                               
'KKNIF_DELAY,', ...                             
'MACOUT_RSBIT,', ...                            
'INPX_LAYER_ID_0,', ...                         
'INPX_LAYER_ID_1,', ...                         
'INPX_LAYER_ID_2,', ...                         
'INPX_LAYER_ID_3,', ...                         
'INPX_LAYER_ID_4,', ...                         
'INPX_LAYER_ID_5,', ...                         
'INPX_LAYER_ID_6,', ...                         
'INPX_LAYER_ID_7,', ...                         
'INPX_LAYER_ID_8,', ...                         
'INPX_LAYER_ID_9,', ...                         
'INPX_LAYER_ID_10,', ...                        
'INPX_LAYER_ID_11,', ...                        
'INPX_LAYER_ID_12,', ...                        
'INPX_LAYER_ID_13,', ...                        
'INPX_LAYER_ID_14,', ...                        
'INPX_LAYER_ID_15,', ...                        
'INPX_NUM_LAYER,', ...                          
'INPX_CMD_SIZE,', ...                           
'INPX_ADDR_ADJUST,', ...                        
'WT_ADDR,', ...                                 
'WT_CMD_SIZE,', ...                             
'OUTPX_ADDR,', ...                              
'OUTPX_CMD_SIZE,', ...                          
'NUM_TIF,', ...                                 
'NUM_TOY,', ...                                 
'NUM_TOF,', ...                                 
'NUM_TBX,', ...                                 
'OFFSET_TIY,', ...                              
'OFFSET_WT_TOF,', ...                           
'OFFSET_TOY,', ...                              
'OFFSET_TOF,', ...                              
'OFFSET_OF,', ...                               
'BUFS_PXIN_DEPTHS,', ...                        
'BUFS_PXOU_DEPTHS,', ...                        
'NUM_ADDRS_1BOX_M1,', ...                       
'NIX_NUM_ADDRS,', ...                           
'NUM_VALID_PX_M1,', ...                         
'NUM_BOX_1BUF_M1,', ...                         
'NUM_NIX_INPX2,', ...                           
'NIF_FCON_M1,', ...                             
'NOF1POF_FCON_M1,', ...                         
'ROI_TILES_FCON_M1,', ...                       
'DIVISION_GAP,', ...                            
'NUM_DDR_WORDS_GAP,', ...                       
'NUM_SKIP_RDADDR_WORDS_GAP,', ...               
'NUM_VALID_RDADDR_WORDS_GAP,', ...  
'SPATIAL_SCALE,', ...                          
'POOL_SIZE,', ...                               
'GRID_DIVISION_EQUIVALENT,', ...                
'NUM_FRACTIONAL_BITS,', ...                     
'NUM_CHANNELS,', ...                            
'NUM_CHANNELS_PER_BUFFER,', ...                 
'CH_HEIGHT_ROIPL,', ...                         
'CH_WIDTH_ROIPL,', ...                         
'IMG_W,', ...                                   
'IMG_H,', ...                                   
'MIN_W,', ...                                   
'MIN_H,', ...                                   
'CH_HEIGHT_PROP,', ...                          
'CH_WIDTH_PROP,', ...                           
'NUM_ANCHORS,', ...                             
'NUM_ANCHORS_PER_BUFFER,', ...      
'NUM_STDDEV,', ...                              
'NMS_THRESHOLD,', ...                           
'NUM_POST_NMS,', ...
'DIV_BY_N,', ...                                
'ANCHOR_CTR_X,', ...                            
'ANCHOR_CTR_Y,', ...                            
'ANCHOR_W_0,', ...                              
'ANCHOR_W_1,', ...                              
'ANCHOR_W_2,', ...                              
'ANCHOR_W_3,', ...                              
'ANCHOR_W_4,', ...                              
'ANCHOR_W_5,', ...                              
'ANCHOR_W_6,', ...                              
'ANCHOR_W_7,', ...                              
'ANCHOR_W_8,', ...                              
'ANCHOR_W_9,', ...                              
'ANCHOR_W_10,', ...                             
'ANCHOR_W_11,', ...                             
'ANCHOR_W_12,', ...                             
'ANCHOR_W_13,', ...                             
'ANCHOR_W_14,', ...                             
'ANCHOR_W_15,', ...                             
'ANCHOR_W_16,', ...                             
'ANCHOR_W_17,', ...                             
'ANCHOR_W_18,', ...                             
'ANCHOR_W_19,', ...                             
'ANCHOR_W_20,', ...                             
'ANCHOR_W_21,', ...                             
'ANCHOR_W_22,', ...                             
'ANCHOR_W_23,', ...                             
'ANCHOR_W_24,', ...                             
'ANCHOR_W_25,', ...                             
'ANCHOR_W_26,', ...                             
'ANCHOR_W_27,', ...                             
'ANCHOR_W_28,', ...                             
'ANCHOR_W_29,', ...                             
'ANCHOR_W_30,', ...                             
'ANCHOR_W_31,', ...                             
'ANCHOR_W_32,', ...                             
'ANCHOR_W_33,', ...                             
'ANCHOR_W_34,', ...                             
'ANCHOR_W_35,', ...                             
'ANCHOR_W_36,', ...                             
'ANCHOR_W_37,', ...                             
'ANCHOR_W_38,', ...                             
'ANCHOR_W_39,', ...                             
'ANCHOR_W_40,', ...                             
'ANCHOR_W_41,', ...                             
'ANCHOR_W_42,', ...                             
'ANCHOR_W_43,', ...                             
'ANCHOR_W_44,', ...                             
'ANCHOR_W_45,', ...                             
'ANCHOR_W_46,', ...                             
'ANCHOR_W_47,', ...                             
'ANCHOR_W_48,', ...                             
'ANCHOR_W_49,', ...                             
'ANCHOR_W_50,', ...                             
'ANCHOR_W_51,', ...                             
'ANCHOR_W_52,', ...                             
'ANCHOR_W_53,', ...                             
'ANCHOR_W_54,', ...                             
'ANCHOR_W_55,', ...                             
'ANCHOR_W_56,', ...                             
'ANCHOR_W_57,', ...                             
'ANCHOR_W_58,', ...                             
'ANCHOR_W_59,', ...                             
'ANCHOR_W_60,', ...                             
'ANCHOR_W_61,', ...                             
'ANCHOR_W_62,', ...                             
'ANCHOR_W_63,', ...                             
'ANCHOR_H_0,', ...                              
'ANCHOR_H_1,', ...                              
'ANCHOR_H_2,', ...                              
'ANCHOR_H_3,', ...                              
'ANCHOR_H_4,', ...                              
'ANCHOR_H_5,', ...                              
'ANCHOR_H_6,', ...                              
'ANCHOR_H_7,', ...                              
'ANCHOR_H_8,', ...                              
'ANCHOR_H_9,', ...                              
'ANCHOR_H_10,', ...                             
'ANCHOR_H_11,', ...                             
'ANCHOR_H_12,', ...                             
'ANCHOR_H_13,', ...                             
'ANCHOR_H_14,', ...                             
'ANCHOR_H_15,', ...                             
'ANCHOR_H_16,', ...                             
'ANCHOR_H_17,', ...                             
'ANCHOR_H_18,', ...                             
'ANCHOR_H_19,', ...                             
'ANCHOR_H_20,', ...                             
'ANCHOR_H_21,', ...                             
'ANCHOR_H_22,', ...                             
'ANCHOR_H_23,', ...                             
'ANCHOR_H_24,', ...                             
'ANCHOR_H_25,', ...                             
'ANCHOR_H_26,', ...                             
'ANCHOR_H_27,', ...                             
'ANCHOR_H_28,', ...                             
'ANCHOR_H_29,', ...                             
'ANCHOR_H_30,', ...                             
'ANCHOR_H_31,', ...                             
'ANCHOR_H_32,', ...                             
'ANCHOR_H_33,', ...                             
'ANCHOR_H_34,', ...                             
'ANCHOR_H_35,', ...                             
'ANCHOR_H_36,', ...                             
'ANCHOR_H_37,', ...                             
'ANCHOR_H_38,', ...                             
'ANCHOR_H_39,', ...                             
'ANCHOR_H_40,', ...                             
'ANCHOR_H_41,', ...                             
'ANCHOR_H_42,', ...                             
'ANCHOR_H_43,', ...                             
'ANCHOR_H_44,', ...                             
'ANCHOR_H_45,', ...                             
'ANCHOR_H_46,', ...                             
'ANCHOR_H_47,', ...                             
'ANCHOR_H_48,', ...                             
'ANCHOR_H_49,', ...                             
'ANCHOR_H_50,', ...                             
'ANCHOR_H_51,', ...                             
'ANCHOR_H_52,', ...                             
'ANCHOR_H_53,', ...                             
'ANCHOR_H_54,', ...                             
'ANCHOR_H_55,', ...                             
'ANCHOR_H_56,', ...                             
'ANCHOR_H_57,', ...                             
'ANCHOR_H_58,', ...                             
'ANCHOR_H_59,', ...                             
'ANCHOR_H_60,', ...                             
'ANCHOR_H_61,', ...                             
'ANCHOR_H_62,', ...                             
'ANCHOR_H_63,', ...                  
'\n'
]);         


for L = 1:NUM_LAYER
                        % compiler variable                       % register names
    fprintf(fid, '%d,',                                      L ); % 'idx,', ...              
    fprintf(fid, '%d,', NUM_LAYER                              ); % 'NUM_LAYER,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_LAYER_TYPE                 (L)); % 'LAYER_TYPE,', ...         
    fprintf(fid, '%d,', CR_LAYER_INPX_BUF_MODE              (L)); % 'INPX_BUF_MODE,', ...         
    fprintf(fid, '%d,', CR_LAYER_WT_BUF_MODE                (L)); % 'WT_BUF_MODE,', ...         
    fprintf(fid, '%d,', CR_LAYER_OUTPX_BUF_MODE             (L)); % 'OUTPX_BUF_MODE,', ...         
    fprintf(fid, '%d,', CR_LAYER_PAD                        (L)); % 'PAD,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_STRIDE                     (L)); % 'STRIDE,', ...
    fprintf(fid, '%d,', CR_LAYER_RDADDR_ROTATE_EN           (L)); % 'RDADDR_ROTATE_EN,', ...
    fprintf(fid, '%d,', CR_LAYER_TIX                        (L)); % 'TIX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TIY                        (L)); % 'TIY,', ...                                             % NOTE: actuall value! NO minus 1                                                   
    fprintf(fid, '%d,', CR_LAYER_TIF                        (L)); % 'TIF,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TOF                        (L)); % 'TOF,', ...                            
    fprintf(fid, '%d,', CR_LAYER_with_ReLU                  (L)); % 'WITH_RELU,', ...                
    fprintf(fid, '%d,', CR_LAYER_with_Bias                  (L)); % 'WITH_BIAS,', ...                                                 
    fprintf(fid, '%d,', CR_LAYER_NIX1BUF                    (L)); % 'INBUF_RDADDR_KEY,', ...
    fprintf(fid, '%d,', CR_LAYER_KXKY_CV_M1                 (L)); % 'KX_KY,', ...
    fprintf(fid, '%d,', CR_LAYER_NKX_M1                     (L)); % 'NKX,', ...
    fprintf(fid, '%d,', CR_LAYER_NKY_M1                     (L)); % 'NKY,', ... 
    fprintf(fid, '%d,', CR_LAYER_PAD_DIV_STRIDE             (L)); % 'PAD_DIV_STRIDE,', ...
    fprintf(fid, '%d,', CR_LAYER_LBUF_WREN                  (L)); % 'LBUF_WREN,', ...
    fprintf(fid, '%d,', CR_LAYER_LBUF_RDEN                  (L)); % 'LBUF_RDEN,', ...
    fprintf(fid, '%d,', CR_LAYER_TOY_IS_NOY                 (L)); % 'TOY_IS_NOY,', ...
    fprintf(fid, '%d,', CR_LAYER_MAX_PAD_STR                (L)); % 'MAX_PAD_STR,', ...
    fprintf(fid, '%d,', CR_LAYER_TOX_GRP_M1                 (L)); % 'TOX_GRP,', ...                        
    fprintf(fid, '%d,', CR_LAYER_TOY_GRP_M1                 (L)); % 'TOY_GRP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TOF_GRP_M1                 (L)); % 'TOF_GRP,', ...     
    fprintf(fid, '%d,', CR_LAYER_TOXDMA_GRP                 (L)); % 'TOXDMA_GRP,', ...
    fprintf(fid, '%d,', CR_LAYER_END_TOYPAD_M1              (L)); % 'END_TOYPAD,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_END_NOYPAD_M1              (L)); % 'END_NOYPAD,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_PAD_E_CV_POX               (L)); % 'PAD_E_CV_POX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_PAD_S_CV_POY               (L)); % 'PAD_S_CV_POY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_PAD_E_CV_NKX               (L)); % 'PAD_E_CV_NKX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_PAD_S_CV_NKY               (L)); % 'PAD_S_CV_NKY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_PAD_N_CV_POY               (L)); % 'PAD_N_CV_POY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_PAD_N_CV_NKY               (L)); % 'PAD_N_CV_NKY,', ...                                                
    fprintf(fid, '%d,', CR_LAYER_PADE_END_PLMX              (L)); % 'PAD_E_END_PLMX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_PADS_END_PLMX              (L)); % 'PAD_S_END_PLMX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TIXGRP_PLMX                (L)); % 'NUM_TIXGRP_PLMX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TIXGRP1ST_PLMX             (L)); % 'TIXGRP1ST_PLMX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TIXY1ST_PLMX               (L)); % 'TIXY1ST_PLMX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_LOC_PAD_E_PLMX             (L)); % 'LOC_PAD_E_PL,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_LOC_PAD_S_PLMX             (L)); % 'LOC_PAD_S_PL,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_WORDS_RDPX_M1              (L)); % 'WORDS_RDPX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_WORDS_WRPX_M1              (L)); % 'WORDS_WRPX,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_ROWSTR                 (L)); % 'NUM_ROWSTR,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_END_ROW                    (L)); % 'END_ROW,', ...                                                                                
    fprintf(fid, '%d,', CR_LAYER_END_ROWSTR                 (L)); % 'END_ROW_STR,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TOF1OUPX_BSCV              (L)); % 'TOF1OUPX_BSCV,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_ACCU_TOF_BSCV              (L)); % 'ACCU_TOF_BSCV,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NOY_GRP_M1                 (L)); % 'NOY_GRP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NOF_GRP_M1                 (L)); % 'NOF_GRP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TIX1POX_STR                (L)); % 'TIX1POX_STR,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TIX1POX_TIY1POY            (L)); % 'TIX1POX_TIY1POY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_END_ROWPOY                 (L)); % 'END_ROWPOY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TOXGRP_POY                 (L)); % 'TOXGRP_POY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_TOXGRP_TOY                 (L)); % 'TOXGRP_TOY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_KX_KY_TIF                  (L)); % 'KX_KY_TIF,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_KKNIF_DELAY                (L)); % 'KKNIF_DELAY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_MACOUT_RSBIT               (L)); % 'MACOUT_RSBIT,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_1            (L)); % 'INPX_LAYER_ID_0,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_2            (L)); % 'INPX_LAYER_ID_1,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_3            (L)); % 'INPX_LAYER_ID_2,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_4            (L)); % 'INPX_LAYER_ID_3,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_5            (L)); % 'INPX_LAYER_ID_4,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_6            (L)); % 'INPX_LAYER_ID_5,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_7            (L)); % 'INPX_LAYER_ID_6,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_8            (L)); % 'INPX_LAYER_ID_7,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_9            (L)); % 'INPX_LAYER_ID_8,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_10           (L)); % 'INPX_LAYER_ID_9,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_11           (L)); % 'INPX_LAYER_ID_10,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_12           (L)); % 'INPX_LAYER_ID_11,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_13           (L)); % 'INPX_LAYER_ID_12,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_14           (L)); % 'INPX_LAYER_ID_13,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_15           (L)); % 'INPX_LAYER_ID_14,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_layer_id_16           (L)); % 'INPX_LAYER_ID_15,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_num_layer             (L)); % 'INPX_NUM_LAYER,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_cmd_size              (L)); % 'INPX_CMD_SIZE,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inpx_addr_adjust           (L)); % 'INPX_ADDR_ADJUST,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inwt_addr                  (L)); % 'WT_ADDR,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_inwt_cmd_size              (L)); % 'WT_CMD_SIZE,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_outpx_addr                 (L)); % 'OUTPX_ADDR,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_outpx_cmd_size             (L)); % 'OUTPX_CMD_SIZE,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_num_tif                    (L)); % 'NUM_TIF,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_num_toy                    (L)); % 'NUM_TOY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_num_tof                    (L)); % 'NUM_TOF,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_num_tbx                    (L)); % 'NUM_TBX,', ...                                                                                
    fprintf(fid, '%d,', CR_LAYER_offset_tiy                 (L)); % 'OFFSET_TIY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_offset_wt_tof              (L)); % 'OFFSET_WT_TOF,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_offset_toy                 (L)); % 'OFFSET_TOY,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_offset_tof                 (L)); % 'OFFSET_TOF,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_offset_of                  (L)); % 'OFFSET_OF,', ...                                                 
    fprintf(fid, '%d,', CR_LAYER_BUFS_PXIN_DEPTHS           (L)); % 'BUFS_PXIN_DEPTHS,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_BUFS_PXOU_DEPTHS           (L)); % 'BUFS_PXOU_DEPTHS,', ...                                                   
    fprintf(fid, '%d,', CR_LAYER_NUM_ADDRS_1BOX_M1          (L)); % 'NUM_ADDRS_1BOX_M1,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NIX_NUM_ADDRS              (L)); % 'NIX_NUM_ADDRS,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_VALID_PX_M1            (L)); % 'NUM_VALID_PX_M1,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_BOX_1BUF_M1            (L)); % 'NUM_BOX_1BUF_M1,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_NIX_INPX2              (L)); % 'NUM_NIX_INPX2,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NIF_FCON_M1                (L)); % 'NIF_FCON_M1,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NOF1POF_FCON_M1            (L)); % 'NOF1POF_FCON_M1,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_ROI_TILES_FCON_M1          (L)); % 'ROI_TILES_FCON_M1,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_DIVISION_GAP               (L)); % 'DIVISION_GAP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_DDR_WORDS_GAP          (L)); % 'NUM_DDR_WORDS_GAP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_SKIP_RDADDR_WORDS_GAP  (L)); % 'NUM_SKIP_RDADDR_WORDS_GAP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_VALID_RDADDR_WORDS_GAP (L)); % 'NUM_VALID_RDADDR_WORDS_GAP,', ...  
    fprintf(fid, '%d,', CR_LAYER_SPATIAL_SCALE              (L)); % 'SPATIAL_SCALE,', ...                                                                                                 
    fprintf(fid, '%d,', CR_LAYER_POOL_SIZE                  (L)); % 'POOL_SIZE,', ...                                                                 
    fprintf(fid, '%d,', CR_LAYER_GRID_DIVISION_EQUIVALENT   (L)); % 'GRID_DIVISION_EQUIVALENT,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_FRACTIONAL_BITS        (L)); % 'NUM_FRACTIONAL_BITS,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_NUM_CHANNELS               (L)); % 'NUM_CHANNELS,', ...                                                              
    fprintf(fid, '%d,', CR_LAYER_NUM_CHANNELS_PER_BUFFER    (L)); % 'NUM_CHANNELS_PER_BUFFER,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_CH_HEIGHT_ROIPL            (L)); % 'CH_HEIGHT_ROIPL,', ...                                                                              
    fprintf(fid, '%d,', CR_LAYER_CH_WIDTH_ROIPL             (L)); % 'CH_WIDTH_ROIPL', ...                                                                                  
    fprintf(fid, '%d,', CR_LAYER_img_w                      (L)); % 'IMG_W,', ...                                                                     
    fprintf(fid, '%d,', CR_LAYER_img_h                      (L)); % 'IMG_H,', ...                                                                     
    fprintf(fid, '%d,', CR_LAYER_min_w                      (L)); % 'MIN_W,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_min_h                      (L)); % 'MIN_H,', ...                                                          
    fprintf(fid, '%d,', CR_LAYER_ch_height                  (L)); % 'CH_HEIGHT_PROP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_ch_width                   (L)); % 'CH_WIDTH_PROP,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_num_anchors                (L)); % 'NUM_ANCHORS,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_num_anchors_per_buffer     (L)); % 'NUM_ANCHORS_PER_BUFFER,', ...      
    fprintf(fid, '%d,', CR_LAYER_num_stddev                 (L)); % 'NUM_STDDEV,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_nms_threshold              (L)); % 'NMS_THRESHOLD,', ...                                                  
    fprintf(fid, '%d,', CR_LAYER_numPostNMS                 (L)); % 'NUM_POST_NMS,', ...
    fprintf(fid, '%d,', CR_LAYER_div_by_n_correction        (L)); % 'DIV_BY_N,', ...                                                                      
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_CTR_X               (L)); % 'ANCHOR_CTR_X,', ...                                                          
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_CTR_Y               (L)); % 'ANCHOR_CTR_Y,', ...                             
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,01)); % 'ANCHOR_W_0,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,02)); % 'ANCHOR_W_1,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,03)); % 'ANCHOR_W_2,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,04)); % 'ANCHOR_W_3,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,05)); % 'ANCHOR_W_4,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,06)); % 'ANCHOR_W_5,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,07)); % 'ANCHOR_W_6,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,08)); % 'ANCHOR_W_7,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,09)); % 'ANCHOR_W_8,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,10)); % 'ANCHOR_W_9,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,11)); % 'ANCHOR_W_10,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,12)); % 'ANCHOR_W_11,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,13)); % 'ANCHOR_W_12,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,14)); % 'ANCHOR_W_13,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,15)); % 'ANCHOR_W_14,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,16)); % 'ANCHOR_W_15,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,17)); % 'ANCHOR_W_16,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,18)); % 'ANCHOR_W_17,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,19)); % 'ANCHOR_W_18,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,20)); % 'ANCHOR_W_19,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,21)); % 'ANCHOR_W_20,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,22)); % 'ANCHOR_W_21,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,23)); % 'ANCHOR_W_22,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,24)); % 'ANCHOR_W_23,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,25)); % 'ANCHOR_W_24,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,26)); % 'ANCHOR_W_25,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,27)); % 'ANCHOR_W_26,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,28)); % 'ANCHOR_W_27,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,29)); % 'ANCHOR_W_28,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,30)); % 'ANCHOR_W_29,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,31)); % 'ANCHOR_W_30,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,32)); % 'ANCHOR_W_31,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,33)); % 'ANCHOR_W_32,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,34)); % 'ANCHOR_W_33,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,35)); % 'ANCHOR_W_34,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,36)); % 'ANCHOR_W_35,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,37)); % 'ANCHOR_W_36,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,38)); % 'ANCHOR_W_37,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,39)); % 'ANCHOR_W_38,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,40)); % 'ANCHOR_W_39,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,41)); % 'ANCHOR_W_40,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,42)); % 'ANCHOR_W_41,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,43)); % 'ANCHOR_W_42,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,44)); % 'ANCHOR_W_43,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,45)); % 'ANCHOR_W_44,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,46)); % 'ANCHOR_W_45,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,47)); % 'ANCHOR_W_46,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,48)); % 'ANCHOR_W_47,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,49)); % 'ANCHOR_W_48,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,50)); % 'ANCHOR_W_49,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,51)); % 'ANCHOR_W_50,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,52)); % 'ANCHOR_W_51,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,53)); % 'ANCHOR_W_52,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,54)); % 'ANCHOR_W_53,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,55)); % 'ANCHOR_W_54,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,56)); % 'ANCHOR_W_55,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,57)); % 'ANCHOR_W_56,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,58)); % 'ANCHOR_W_57,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,59)); % 'ANCHOR_W_58,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,60)); % 'ANCHOR_W_59,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,61)); % 'ANCHOR_W_60,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,62)); % 'ANCHOR_W_61,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,63)); % 'ANCHOR_W_62,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_W                (L,64)); % 'ANCHOR_W_63,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,01)); % 'ANCHOR_H_0,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,02)); % 'ANCHOR_H_1,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,03)); % 'ANCHOR_H_2,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,04)); % 'ANCHOR_H_3,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,05)); % 'ANCHOR_H_4,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,06)); % 'ANCHOR_H_5,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,07)); % 'ANCHOR_H_6,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,08)); % 'ANCHOR_H_7,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,09)); % 'ANCHOR_H_8,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,10)); % 'ANCHOR_H_9,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,11)); % 'ANCHOR_H_10,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,12)); % 'ANCHOR_H_11,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,13)); % 'ANCHOR_H_12,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,14)); % 'ANCHOR_H_13,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,15)); % 'ANCHOR_H_14,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,16)); % 'ANCHOR_H_15,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,17)); % 'ANCHOR_H_16,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,18)); % 'ANCHOR_H_17,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,19)); % 'ANCHOR_H_18,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,20)); % 'ANCHOR_H_19,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,21)); % 'ANCHOR_H_20,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,22)); % 'ANCHOR_H_21,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,23)); % 'ANCHOR_H_22,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,24)); % 'ANCHOR_H_23,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,25)); % 'ANCHOR_H_24,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,26)); % 'ANCHOR_H_25,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,27)); % 'ANCHOR_H_26,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,28)); % 'ANCHOR_H_27,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,29)); % 'ANCHOR_H_28,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,30)); % 'ANCHOR_H_29,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,31)); % 'ANCHOR_H_30,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,32)); % 'ANCHOR_H_31,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,33)); % 'ANCHOR_H_32,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,34)); % 'ANCHOR_H_33,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,35)); % 'ANCHOR_H_34,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,36)); % 'ANCHOR_H_35,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,37)); % 'ANCHOR_H_36,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,38)); % 'ANCHOR_H_37,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,39)); % 'ANCHOR_H_38,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,40)); % 'ANCHOR_H_39,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,41)); % 'ANCHOR_H_40,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,42)); % 'ANCHOR_H_41,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,43)); % 'ANCHOR_H_42,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,44)); % 'ANCHOR_H_43,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,45)); % 'ANCHOR_H_44,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,46)); % 'ANCHOR_H_45,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,47)); % 'ANCHOR_H_46,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,48)); % 'ANCHOR_H_47,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,49)); % 'ANCHOR_H_48,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,50)); % 'ANCHOR_H_49,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,51)); % 'ANCHOR_H_50,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,52)); % 'ANCHOR_H_51,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,53)); % 'ANCHOR_H_52,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,54)); % 'ANCHOR_H_53,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,55)); % 'ANCHOR_H_54,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,56)); % 'ANCHOR_H_55,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,57)); % 'ANCHOR_H_56,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,58)); % 'ANCHOR_H_57,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,59)); % 'ANCHOR_H_58,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,60)); % 'ANCHOR_H_59,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,61)); % 'ANCHOR_H_60,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,62)); % 'ANCHOR_H_61,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,63)); % 'ANCHOR_H_62,', ...                                                         
    fprintf(fid, '%d,', CR_LAYER_ANCHOR_H                (L,64)); % 'ANCHOR_H_63,', ...                                                                                  
    fprintf(fid, '\n');
end 

fclose(fid);


