cnt_CONV = 1;
cnt_FCON = 1;

cnt_LAYER = ID_global_CONV(cnt_CONV);

fid = fopen('param_compute_arch_macs.v','w');

fprintf(fid, '// Generated by %s.m \n\n\n', mfilename);



fprintf(fid, 'assign CR_TIF_M1              = %d; \n', CR_LAYER_TIF             (cnt_LAYER));
fprintf(fid, 'assign CR_TOX_GRP_M1          = %d; \n', CR_LAYER_TOX_GRP_M1		(cnt_LAYER));
fprintf(fid, 'assign CR_TOY_GRP_M1          = %d; \n', CR_LAYER_TOY_GRP_M1		(cnt_LAYER));
fprintf(fid, 'assign CR_TOF_GRP_M1          = %d; \n', CR_LAYER_TOF_GRP_M1		(cnt_LAYER));
fprintf(fid, 'assign CR_KX_KY_TIF           = %d; \n', CR_LAYER_KX_KY_TIF		(cnt_LAYER));
fprintf(fid, 'assign CR_NIX1BUF             = %d; \n', CR_LAYER_NIX1BUF         (cnt_LAYER));
fprintf(fid, 'assign CR_TIX1POX_STR         = %d; \n', CR_LAYER_TIX1POX_STR		(cnt_LAYER));
fprintf(fid, 'assign CR_TIX1POX_TIY1POY     = %d; \n', CR_LAYER_TIX1POX_TIY1POY	(cnt_LAYER));
fprintf(fid, 'assign CR_NOY_GRP_M1          = %d; \n', CR_LAYER_NOY_GRP_M1		(cnt_LAYER));
fprintf(fid, 'assign CR_KXKY_CV_M1          = %d; \n', CR_LAYER_KXKY_CV_M1		(cnt_LAYER));
fprintf(fid, 'assign CR_KX_CV_M1            = %d; \n', CR_LAYER_NKX_M1          (cnt_LAYER));
fprintf(fid, 'assign CR_KY_CV_M1            = %d; \n', CR_LAYER_NKY_M1          (cnt_LAYER));
fprintf(fid, 'assign CR_END_TOYPAD_M1       = %d; \n', CR_LAYER_END_TOYPAD_M1	(cnt_LAYER));
fprintf(fid, 'assign CR_END_NOYPAD_M1       = %d; \n', CR_LAYER_END_NOYPAD_M1	(cnt_LAYER));

R_PAD_CV_bin = '';
for x = 1:POX
    bin_tmp = dec2bin(R_PAD_E_CONV_NKX(cnt_CONV,x),WD_KXKY);
    R_PAD_CV_bin = [bin_tmp,R_PAD_CV_bin];
end
fprintf(fid, 'assign CR_PAD_E_CV_NKX        = %d''b%s; \n', WD_KXKY*POX, R_PAD_CV_bin);

R_PAD_CV_bin = '';
for x = 1:POY
    bin_tmp = dec2bin(R_PAD_S_CONV_NKY(cnt_CONV,x),WD_KXKY);
    R_PAD_CV_bin = [bin_tmp,R_PAD_CV_bin];
end
fprintf(fid, 'assign CR_PAD_S_CV_NKY        = %d''b%s; \n', WD_KXKY*POY, R_PAD_CV_bin);

R_PAD_CV_bin = [];
for x = 1:MAX_PAD1STR
    bin_tmp = dec2bin(R_PAD_N_CONV_NKY(cnt_CONV,x),WD_KXKY);
    R_PAD_CV_bin = [bin_tmp,R_PAD_CV_bin];
end
fprintf(fid,'assign CR_PAD_N_CV_NKY         = %d''b%s; \n', WD_KXKY*MAX_PAD1STR, R_PAD_CV_bin);


fprintf(fid, 'assign CR_PAD_E_CV_POX	    = %d; \n', CR_CONV_PAD_E_CV_POX(cnt_CONV));
fprintf(fid, 'assign CR_PAD_S_CV_POY	    = %d; \n', CR_CONV_PAD_S_CV_POY(cnt_CONV));
fprintf(fid, 'assign CR_PAD_N_CV_POY	    = %d; \n', CR_CONV_PAD_N_CV_POY(cnt_CONV));


fprintf(fid, 'assign CR_NOF_GRP_M1	        = %d; \n', CR_LAYER_NOF_GRP_M1   (cnt_LAYER));
fprintf(fid, 'assign CR_TOF1OUPX_BSCV	    = %d; \n', CR_LAYER_TOF1OUPX_BSCV(cnt_LAYER));
fprintf(fid, 'assign CR_ACCU_TOF_BSCV	    = %d; \n', CR_LAYER_ACCU_TOF_BSCV(cnt_LAYER));

fprintf(fid, '\n\n');

fprintf(fid, 'assign csr_W_LBUF_WREN       = %d; \n', CR_LAYER_LBUF_WREN	(cnt_LAYER));
fprintf(fid, 'assign csr_W_LBUF_RDEN       = %d; \n', CR_LAYER_LBUF_RDEN	(cnt_LAYER));
fprintf(fid, 'assign csr_W_MACOUT_RSBIT    = %d; \n', CR_LAYER_MACOUT_RSBIT	(cnt_LAYER));
fprintf(fid, 'assign csr_W_TOX_GRP_M1      = %d; \n', CR_LAYER_TOX_GRP_M1	(cnt_LAYER));
fprintf(fid, 'assign csr_WITH_BIAS         = %d; \n', CR_LAYER_with_Bias	(cnt_LAYER));
fprintf(fid, 'assign csr_WITH_RELU         = %d; \n', CR_LAYER_with_ReLU	(cnt_LAYER));
fprintf(fid, 'assign csr_TIF               = %d; \n', CR_LAYER_TIF   	    (cnt_LAYER));
fprintf(fid, 'assign csr_TOXDMA_GRP        = %d; \n', CR_LAYER_TOXDMA_GRP	(cnt_LAYER));
fprintf(fid, 'assign csr_TOX               = %d; \n', CR_LAYER_TOX_GRP_M1	(cnt_LAYER));
fprintf(fid, 'assign csr_TOY_GRP           = %d; \n', CR_LAYER_TOY_GRP_M1	(cnt_LAYER));
fprintf(fid, 'assign csr_TOF_GRP           = %d; \n', CR_LAYER_TOF_GRP_M1	(cnt_LAYER));
fprintf(fid, 'assign csr_TOXGRP_POY        = %d; \n', CR_LAYER_TOXGRP_POY	(cnt_LAYER));
fprintf(fid, 'assign csr_TOXGRP_TOY        = %d; \n', CR_LAYER_TOXGRP_TOY	(cnt_LAYER));
fprintf(fid, 'assign csr_CONV_DONE_COUNT   = %d; \n', CR_LAYER_KXKY_CV_M1	(cnt_LAYER));
fprintf(fid, 'assign csr_PAD_CONV          = %d; \n', CR_LAYER_PAD       	(cnt_LAYER));


fclose(fid);

fprintf('param_compute_arch_macs.v generated \n\n');