//Generated by DLA_size.m offline 


`ifndef __PARAMETER_DEFINES_PKG_SV__
`define __PARAMETER_DEFINES_PKG_SV__

  package parameter_defines_pkg; 


  localparam SIM_CTRL                               = 1'b0; 
  localparam POX                                    = 08; 
  localparam POY                                    = 08; 
  localparam POF                                    = 32; 
  localparam POX_PL                                 = 32; 
  localparam POY_PL                                 = 01; 
  localparam POF_PL                                 = 08; 
  localparam POF_EW                                 = 08; 
  localparam POF_FC                                 = 32; 
  
  localparam PX_WD                                  = 08; // include sign bit 
  localparam KN_WD_CV                               = 08; // include sign bit 
  localparam KN_WD_FC                               = 08; // include sign bit 
  localparam WD_BSCV                                = 08; // include sign bit 
  localparam WD_BSFC                                = 08; // include sign bit 
  localparam WD_KXKY                                = 04; // support max kernel size of 2^4-1
  localparam MAC_ACCU_WD                            = 6; // additional bit for accumulation 
  
  localparam PX_AD                                  = 32; //# of PX in one addr of INpx BUF 
  localparam POX_2POWER                             = 8; 
  localparam NUM_POX_DMA                            = 4; // = floor(DMA_WIDTH/(Px*WD_PX)) = 4 
  localparam NUM_FC_BOX                             = 1; // # of parallel computed ROIs in FCON 
  localparam MAX_PAD1STR                            = 8; // support max(ceil(PAD_CONV/STR_CONV)) = 8
  localparam POF1OUPX                               = 4; 
  
  
  localparam BUF_INPX_ALL                           = 8; 
  localparam BUF_OUPX_ALL                           = 8; 
  localparam BUF_INPX_1BK                           = 8; 
  localparam BUF_OUPX_1BK                           = 8; 
  
  localparam INWT_WORDS                             = 4096; //BUF_WEIGHT_WORDS            
  localparam INWT_WDAD                              = 14; //BUF_WEIGHT_WDAD+log2(RAM_BK)
  localparam INWT_WD                                = 256; //BUF_WEIGHT_WIDTH            
  localparam INPX_WORDS                             = 2048; //BUF_INPUT_WORDS             
  localparam INPX_WDAD                              = 13; //BUF_INPUT_WDAD+log2(RAM_BK) 
  localparam INPX_WIDTH                             = 64; //BUF_INPUT_WIDTH             
  localparam OUPX_WORD                              = 2048; //BUF_OUTPUT_WORDS            
  localparam OUPX_WDAD                              = 13; //BUF_OUTPUT_WDAD+log2(RAM_BK)
  localparam OUPX_WIDTH                             = 64; //BUF_OUTPUT_WIDTH            
  
  localparam WORD_BSCV                              = 4096; //BUF_BIAS_CONV_WORDS
  localparam WDAD_BSCV                              = 12; //BUF_BIAS_CONV_WDAD 
  localparam WIDTH_BSCV                             = 64; //BUF_BIAS_CONV_WIDTH
  localparam BUF_BIAS_FCON_WORDS                    = 4096; //BUF_BIAS_FCON_WORDS
  localparam BUF_BIAS_FCON_WIDTH                    = 64; //BUF_BIAS_FCON_WIDTH
  localparam BUF_BIAS_FCON_WDAD                     = 12; //BUF_BIAS_FCON_WDAD 
  
  
  
//Proposal
  localparam AN_WD                                  = 16;
  localparam NUM_AN                                 = 64;
  localparam MAX_NUMBER_OF_ROI                      = 300;
  localparam NUM_BIT_NUM_ROI                        = $clog2(MAX_NUMBER_OF_ROI);
  localparam NUM_BIT_DDR_WORD                       =  5; //$clog2(DMA_WIDTH/PX_WD);
  localparam NOY_WRPX_BBOX_OB                       = 80; 
  localparam NOY_WRPX_BBOX_TL                       = 144; 
  
  
//Global Average Pooling
  localparam WD_ACCU_GAP                            = 16;
  localparam RSBIT_GAP                              = 16;
  localparam WD_DIV_GAP                             = 12;
  
  
  
//Control
  localparam DMA_ADDR_WIDTH                         = 36;
  localparam DMA_DATA_WIDTH                         = 256;
  localparam DMA_CMD_WIDTH                          = 71;
  localparam DMA_ADDR_OFFSET_WIDTH                  = 32;
  localparam DMA_DATA_SIZE_WIDTH                    = 32;
  localparam DMA_SID_WIDTH                          = 6;
  localparam MAP_CNT_WIDTH                          = 15;
  localparam MAP_GRP_CNT_WIDTH                      = 6;
  localparam TILE_CNT_WIDTH                         = 12;
  localparam LAYER_ID_WIDTH                         = 10; // bit width for LAYER ID 
  localparam NUM_CONCAT_LAYER                       = 16; 
  
  
  
//for AHB slave wrapper; SRAM selection parameter
  localparam AHB_DATA_WIDTH                         = 32;
  localparam AHB_RAM_DEC_ADDR_OFFSET                = 'h14000000 +'h20000;
  localparam NUM_RAM                                = 196;
  localparam NUM_RAM_DATA_ROUTER                    = 56;
  localparam NUM_RAM_COMPUTE_ARCH_MAC               = 57;
  localparam INPUT_BUF_RAM_SEL_OFFSET               = 0;
  localparam OUTPUT_BUF_RAM_SEL_OFFSET              = 64;
  localparam WEIGHT_BUF_RAM_SEL_OFFSET              = 128;
//localparam OUTPUT_BUF_FC_RAM_SEL_OFFSET           = 136;
//localparam DMA_CONTROL_RAM_SEL_BASE               = 141;  //Base DMA cotrol
//localparam DESCRIPTOR_WR_CV_RAM_SEL_OFFSET        = 0;
//localparam DESCRIPTOR_RD_CV_RAM_SEL_OFFSET        = 1;
//localparam DESCRIPTOR_WR_PL_RAM_SEL_OFFSET        = 2;
//localparam DESCRIPTOR_RD_PL_RAM_SEL_OFFSET        = 3;
//localparam DESCRIPTOR_SIZE_WR_CV_RAM_SEL_OFFSET   = 145;
//localparam DESCRIPTOR_SIZE_RD_CV_RAM_SEL_OFFSET   = 146;
//localparam DESCRIPTOR_SIZE_WR_PL_RAM_SEL_OFFSET   = 147;
//localparam DESCRIPTOR_SIZE_RD_PL_RAM_SEL_OFFSET   = 148;
//localparam ROI_RAM_SEL_OFFSET                     = 149;
  localparam BIAS_FC_RAM_SEL_OFFSET                 = 136;
  localparam COMPUTE_ARCH_MAC_RAM_SEL_BASE          = 137;  //Base compute_arc_mac
  localparam BIAS_CONV_RAM_SEL_OFFSET               = 0;
  localparam DATA_ROUTER_RAM_SEL_BASE               = 1;    //Base data_router
  localparam LINE_BUFFER_ROUTER_RAM_SEL_OFFSET      = 0;    
//localparam PADSHIFT_K07S2P3_RAM_SEL_OFFSET        = 56;
//localparam PADSHIFT_K03S1P1_RAM_SEL_OFFSET        = 80;
//localparam PADSHIFT_K06S2P1_RAM_SEL_OFFSET        = 88;
//localparam PADSHIFT_K05S1P2_RAM_SEL_OFFSET        = 96;
  localparam LAYER_LUT_RAM_SEL_OFFSET               = 194;
  localparam CONFIG_REG_RAM_SEL_OFFSET              = 195;
  
  
  endpackage 

`endif 

